# ============================================================
#  Debezium Server — La Barca
#  Source: MySQL (CDC)  ->  Sink: PostgreSQL (raw schema)
# ============================================================

# SOURCE: conector MySQL
debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
debezium.source.topic.prefix=labarca
debezium.source.database.hostname=labarca-oltp-mysql
debezium.source.database.port=3306
debezium.source.database.user=airbyte_cdc
debezium.source.database.password=cdc1234
debezium.source.database.server.id=9999
debezium.source.database.include.list=labarca_oltp
debezium.source.table.include.list=labarca_oltp.ventas

debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=5000
debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/debezium/data/schema-history.dat

debezium.source.snapshot.mode=initial

# SINK: PostgreSQL via JDBC
debezium.sink.type=jdbc
debezium.sink.jdbc.url=jdbc:postgresql://labarca-dw-pg:5432/labarca_dw
debezium.sink.jdbc.username=dbt_user
debezium.sink.jdbc.password=dbt1234

debezium.sink.jdbc.schema.evolution=basic
debezium.sink.jdbc.insert.mode=upsert
debezium.sink.jdbc.primary.key.mode=record_key
debezium.sink.jdbc.delete.enabled=true

# mapea el topic labarca.labarca_oltp.ventas -> tabla raw.ventas
debezium.transforms=route
debezium.transforms.route.type=org.apache.kafka.connect.transforms.RegexRouter
debezium.transforms.route.regex=labarca\\.labarca_oltp\\.(.*)
debezium.transforms.route.replacement=raw.$1

quarkus.log.level=INFO
quarkus.log.category."io.debezium".level=INFO
